apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

resources:
  - namespace.yaml
  - ../../base/api-service
  - ../../components/hpa
  - ../../components/network-policies
  - ../../components/monitoring

namePrefix: dev-

labels:
  - pairs:
      environment: development
      team: platform
  
commonAnnotations:
  environment: development
  managed-by: kustomize

replicas:
  - name: api-service
    count: 1 # Single replica for dev

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: api-service
    path: deployment-patch.yaml
  - target:
      group: autoscaling
      version: v2
      kind: HorizontalPodAutoscaler
      name: api-service-hpa
    path: hpa-patch.yaml
  - target:
      version: v1
      kind: ConfigMap
      name: api-config
    path: configmap-patch.yaml

secretGenerator:
  - name: api-secrets-env
    literals:
      - DATABASE_URL=postgresql://dev_user:dev_pass@postgres-dev:5432/api_dev
      - REDIS_URL=redis://redis-dev:6379/0
      - JWT_SECRET=dev-secret-key-not-for-production
      - API_KEY=dev-api-key
      - INTERNAL_API_KEY=dev-internal-api-key
      - ENCRYPTION_KEY=dev-encryption-key-32-characters

images:
  - name: devx-platform/api
    newTag: dev-latest