apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: devx-platform
  labels:
    app: api-service
    component: service-mesh
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: api-service-authz
  namespace: devx-platform
  labels:
    app: api-service
    component: service-mesh
spec:
  selector:
    matchLabels:
      app: api-service
  action: ALLOW
  rules:
  # Allow all internal mesh traffic
  - from:
    - source:
        principals: ["cluster.local/ns/devx-platform/sa/*"]
  # Allow specific service accounts
  - from:
    - source:
        principals: 
        - "cluster.local/ns/devx-platform/sa/frontend-service"
        - "cluster.local/ns/devx-platform/sa/worker-service"
    to:
    - operation:
        methods: ["GET", "POST", "PUT", "DELETE"]
  # Allow health checks
  - to:
    - operation:
        paths: ["/health/*"]
  # Rate limit by IP
  - when:
    - key: request.headers[x-forwarded-for]
      values: ["*"]