{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-secrets
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
---
{{- end }}
{{- if .Values.featureFlags.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-feature-flags
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  sdk-key: {{ .Values.featureFlags.sdkKey | b64enc }}
{{- end }}