global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'worker-service'
    static_configs:
      - targets: ['api:9090']
    scrape_interval: 5s
    metrics_path: '/metrics'