apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production
    environment: production
    team: platform
  annotations:
    environment: production
    managed-by: kustomize