apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

labels:
  - pairs:
      app: api-service
      app.kubernetes.io/name: api-service
      app.kubernetes.io/component: api
      app.kubernetes.io/part-of: devx-platform

commonAnnotations:
  app.kubernetes.io/managed-by: kustomize
  
images:
  - name: devx-platform/api
    newName: devx-platform/api
    newTag: latest