apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml

commonLabels:
  app.kubernetes.io/component: api
  app.kubernetes.io/part-of: platform

configMapGenerator:
  - name: api-config
    behavior: merge
    files:
      - config/application.yaml

secretGenerator:
  - name: api-secrets
    behavior: merge
    envs:
      - secrets/.env.secret