apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  labels:
    app: api-service
type: Opaque
stringData:
  # Database configuration
  DATABASE_URL: "postgresql://user:password@postgres-service:5432/devx_platform"
  DATABASE_SSL_MODE: "require"
  
  # Redis configuration
  REDIS_URL: "redis://redis-service:6379/0"
  REDIS_PASSWORD: "your-redis-password-here"
  
  # Authentication secrets
  JWT_SECRET: "your-jwt-secret-here-minimum-32-characters-long"
  JWT_EXPIRATION: "24h"
  REFRESH_TOKEN_SECRET: "your-refresh-token-secret-here-minimum-32-chars"
  
  # API Keys
  API_KEY: "your-api-key-here"
  INTERNAL_API_KEY: "your-internal-api-key-here"
  
  # Encryption keys
  ENCRYPTION_KEY: "your-encryption-key-here-32-characters"
  
  # External service credentials
  AWS_ACCESS_KEY_ID: "your-aws-access-key-id"
  AWS_SECRET_ACCESS_KEY: "your-aws-secret-access-key"
  
  # Monitoring
  SENTRY_DSN: "https://your-sentry-dsn@sentry.io/project-id"
  
  # OAuth credentials (if needed)
  OAUTH_CLIENT_ID: "your-oauth-client-id"
  OAUTH_CLIENT_SECRET: "your-oauth-client-secret"