apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
stringData:
  # Example secrets - replace with actual values
  DATABASE_URL: "postgresql://user:password@db-host:5432/dbname"
  REDIS_URL: "redis://redis-host:6379/0"
  JWT_SECRET: "your-jwt-secret-here"
  API_KEY: "your-api-key-here"
  ENCRYPTION_KEY: "your-encryption-key-here"