global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'grpc-service'
    static_configs:
      - targets: ['grpc-service:9090']
    scrape_interval: 5s
    metrics_path: '/metrics'